definitions:
  model.Student:
    type: object
info:
  contact: {}
paths:
  /example/hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /student:
    put:
      description: 创建学生
      parameters:
      - description: 姓名
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/model.Student'
      produces:
      - application/json
      responses:
        "200":
          description: 学生
          schema:
            type: string
      summary: student example
      tags:
      - example
  /system/health:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: health check
      tags:
      - example
  /system/monitor:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: monitor
      tags:
      - example
swagger: "2.0"
